config/routes.rb
Rails.application.routes.draw do
  get 'user/index', to: "users#index"

  get 'user/prodile', to: "users#profile"
  get 'ad_holders/update_makes', to: 'ad_holders#update_makes', as: 'update_makes'

  devise_for :users, :controllers => 
  { :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions" }
  resources :ad_holders
  root "application#landing"

end

app/models/ad_holder.rb
class AdHolder < ActiveRecord::Base
	has_many :images, :foreign_key => "holder_id"
	has_one :vehicle_model_year, :foreign_key => "car_id"
	validates_presence_of :holder_type, :price, :car_id
	accepts_nested_attributes_for :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :ad_holder, :foreign_key => "holder_id"
	mount_uploader :file, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	  end
	end

  def name
    self.email
  end
end

app/models/vehicle_model_year.rb
class VehicleModelYear < ActiveRecord::Base
end

app/controllers/ad_holders_controller.rb
class AdHoldersController < ApplicationController
  before_action :set_ad_holder, only: [:show, :edit, :update, :destroy]

  # GET /ad_holders
  # GET /ad_holders.json
  def index
    @ad_holders = AdHolder.all
  end

  # GET /ad_holders/1
  # GET /ad_holders/1.json
  def show
  end

  # GET /ad_holders/new
  def new
    @makes = VehicleModelYear.uniq.pluck(:make).sort!
    @vehicles = []
    @ad_holder = AdHolder.new
    3.times do
      @ad_holder.images.build
    end
  end

  # update make 
  def update_makes
    @vehicles =VehicleModelYear.where("make= ?", params[:make]).order(:model)
    respond_to do |format|
      format.js
    end
  end



  # GET /ad_holders/1/edit
  def edit
  end

  # POST /ad_holders
  # POST /ad_holders.json
  def create
    @ad_holder = AdHolder.new(ad_holder_params)

    respond_to do |format|
      if @ad_holder.save
        format.html { redirect_to @ad_holder, notice: 'Ad holder was successfully created.' }
        format.json { render :show, status: :created, location: @ad_holder }
      else
        format.html { render :new }
        format.json { render json: @ad_holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_holders/1
  # PATCH/PUT /ad_holders/1.json
  def update
    respond_to do |format|
      puts ad_holder_params
      if @ad_holder.update(ad_holder_params)
        format.html { redirect_to @ad_holder, notice: 'Ad holder was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_holder }
      else
        format.html { render :edit }
        format.json { render json: @ad_holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_holders/1
  # DELETE /ad_holders/1.json
  def destroy
    @ad_holder.destroy
    respond_to do |format|
      format.html { redirect_to ad_holders_url, notice: 'Ad holder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_holder
      @ad_holder = AdHolder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_holder_params
      params.require(:ad_holder).permit(:holder_type, :description, :price, :available, :images_attributes=>["file"])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout false, :only => :landing

  def langing
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    
    def after_sign_up_path_for(resource)
      user_index_path
    end

    def after_inactive_sign_up_path_for(resource)
      new_user_sessions_path
    end


end 

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    
    def after_sign_in_path_for(resource)
      user_index_path
    end

    def after_sign_out_path_for(resource)
      '/'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def prodile
  end
end

app/helpers/ad_holders_helper.rb
module AdHoldersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ad_holders/_form.html.erb
<%= select_tag "make", options_for_select(@makes), id: 'makes_select'%>


<%= form_for(@ad_holder) do |f| %>
  <% if @ad_holder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_holder.errors.count, "error") %> prohibited this ad_holder from being saved:</h2>

      <ul>
      <% @ad_holder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= select_tag :car_id, options_for_select(@vehicles.collect { |vehicle|
    [vehicle.year.to_s + vehicle.model, vehicle.id] }, 0), { id: 'models_select' } %>

  <%=f.fields_for :images do |builder|%>
    <div class="form-group">
      <%= builder.label :file %><br>
      <%= builder.file_field :file, class: "form-control" %>
    </div>
  <%end%>
  
  <div class="form-group">
    <%= f.label :holder_type %><br>
    <%= f.text_field :holder_type, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.text_field :address, id: "location", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :available %><br>
    <%= f.check_box :available, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success"%>
  </div>


<% end %>

app/views/ad_holders/edit.html.erb
<h1>Editing ad_holder</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_holder %> |
<%= link_to 'Back', ad_holders_path %>

app/views/ad_holders/index.html.erb
<h1>Listing ad_holders</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Price</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ad_holders.each do |ad_holder| %>
      <tr>
        <td><%= ad_holder.holder_type %></td>
        <td><%= ad_holder.description %></td>
        <td><%= ad_holder.price %></td>
        <td><%= ad_holder.available %></td>
        <td><%= link_to 'Show', ad_holder %></td>
        <td><%= link_to 'Edit', edit_ad_holder_path(ad_holder) %></td>
        <td><%= link_to 'Destroy', ad_holder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad holder', new_ad_holder_path %>

app/views/ad_holders/new.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>

<div class="container">
	<h1>Register a Car</h1>

	<%= render 'form' %>

	<%= link_to 'Back', ad_holders_path %>
</div>


<%= javascript_include_tag "auto_complete" %>

app/views/ad_holders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @ad_holder.holder_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad_holder.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ad_holder.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @ad_holder.available %>
</p>

<%= link_to 'Edit', edit_ad_holder_path(@ad_holder) %> |
<%= link_to 'Back', ad_holders_path %>

app/views/ad_holders/update_makes.js.erb
$("#models_select").empty().append("<%= escape_javascript(render(:partial => @vehicles)) %>")

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>


    <!-- Custom CSS -->
    <%= stylesheet_link_tag  'business-casual', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Business Casual</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <%= link_to "Login", new_user_session_path%>
                    </li>
                    <li>
                        <%= link_to "Signup", new_user_registration_path%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Business Casual</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Start Bootstrap</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a website
                        <strong>worth visiting</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes
                        <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/views/application/landing.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MoveAd</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <!-- Custom CSS -->
    <%= stylesheet_link_tag  'business-casual', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">MoveAd</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <%= link_to "Login", new_user_session_path%>
                    </li>
                    <li>
                        <%= link_to "Signup", new_user_registration_path%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Business Casual</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Start Bootstrap</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a website
                        <strong>worth visiting</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes
                        <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MoveAd</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Register a car", new_ad_holder_path%></li>
        <li><%= link_to "My Cars", ad_holders_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Log Out", destroy_user_session_path, :method => :delete%></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/index.html.erb
<h1>Index page</h1>

app/views/users/prodile.html.erb
<h1>Users#:prodile</h1>
<p>Find me in app/views/users/:prodile.html.erb</p>

app/views/users/shared/_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
  <div class="container"> 

      <div id="signupbox" style="display:<%= (initial=='signup') && 'block' or 'none'%>; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

          <div class="panel panel-info">
            <div class="panel-heading">
              <div class="panel-title">Sign Up</div>
              <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
            </div>  
            <div class="panel-body" >
              <form id="signupform" class="form-horizontal" role="form">
                
                <div id="signupalert" style="display:none" class="alert alert-danger">
                  <p>Error:</p>
                  <span></span>
                </div>
                  
                
                  
                <div class="form-group">
                  <label for="email" class="col-md-3 control-label">Email</label>
                  <div class="col-md-9">
                    <%= f.email_field :email, autofocus: true, placeholder:"Email Address" ,class:"form-control"%>
                  </div>
                </div>
                  
                <div class="form-group">
                  <label for="firstname" class="col-md-3 control-label">FirstName</label>
                  <div class="col-md-9">
                    <%= f.text_field :first_name, autofocus: true, placeholder:"First Name" ,class:"form-control"%>

                  </div>
                </div>
                <div class="form-group">
                  <label for="lastname" class="col-md-3 control-label">LastName</label>
                  <div class="col-md-9">
                    <%= f.text_field :last_name, autofocus: true , placeholder:"Last Name",class:"form-control"%>

                  </div>
                </div>
                <div class="form-group">
                  <label for="password" class="col-md-3 control-label">Password</label>
                  <div class="col-md-9">
                    <%= f.password_field :password, autocomplete: "off",class:"form-control" %>

                  </div>
                </div>
                <div class="form-group">
                  <label for="password" class="col-md-3 control-label">Password Confirmation</label>
                  <div class="col-md-9">
                  <%= f.password_field :password_confirmation, autocomplete: "off",class:"form-control"%>

                  </div>
                </div>

                  

                <div class="form-group">
                  <!-- Button -->                                        
                  <div class="col-md-offset-3 col-md-9">
                    <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                  </div>
                </div>
                

              
              </form>
            
             </div>
          </div>


         
         
        
      </div> 

  </div>
<%end%>
  

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>